/* Service worker: an offline-capable app shell.

   The game is entirely static and has no backend, so every asset can be
   precached at install and served from cache afterwards. That is what lets it
   open on a phone with no signal, and what makes a second launch instant.

   Bump CACHE when the shell changes; the activate handler drops older caches.
   Generated by the build note in README — do not hand-edit ASSETS.

   The boss monsters in assets/ are deliberately NOT precached. They are about a
   megabyte between them, only one species appears per project, and the runtime
   handler below caches each on first use — so a first launch on mobile data
   stays small and the monster is instant every time after. */

const CACHE = 'sds3d-v3';

const ASSETS = [
  "./",
  "./index.html",
  "./manifest.webmanifest",
  "./src/char/poses.js",
  "./src/char/rig.js",
  "./src/core/bake.js",
  "./src/core/color.js",
  "./src/core/gl.js",
  "./src/core/gltf.js",
  "./src/core/math.js",
  "./src/core/meshbuilder.js",
  "./src/game/data.js",
  "./src/game/dialogue.js",
  "./src/game/economy.js",
  "./src/game/furniture.js",
  "./src/game/monsters.js",
  "./src/game/project.js",
  "./src/game/staff.js",
  "./src/game/state.js",
  "./src/game/tutorial.js",
  "./src/main.js",
  "./src/render/camera.js",
  "./src/render/renderer.js",
  "./src/render/shaders.js",
  "./src/render/skinned.js",
  "./src/ui/device.js",
  "./src/ui/hud.js",
  "./src/ui/style.css",
  "./src/world/agents.js",
  "./src/world/boss.js",
  "./src/world/office.js",
  "./src/world/palette.js",
  "./src/world/placed.js",
  "./src/world/props.js",
  "./icons/icon-180.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-maskable-512.png",
];

self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    const c = await caches.open(CACHE);
    // addAll rejects the whole install if any single request fails, which on a
    // flaky first load would leave no cache at all. Fetch individually instead.
    await Promise.all(ASSETS.map((u) => c.add(u).catch(() => {})));
    self.skipWaiting();
  })());
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;

  // Navigations go to the network first so a deploy is picked up promptly, and
  // fall back to the cached shell when offline.
  if (req.mode === 'navigate') {
    e.respondWith((async () => {
      try {
        const fresh = await fetch(req);
        const c = await caches.open(CACHE);
        c.put('./index.html', fresh.clone());
        return fresh;
      } catch (err) {
        return (await caches.match('./index.html')) || Response.error();
      }
    })());
    return;
  }

  // Everything else: cache first, then refresh the entry in the background so
  // the next launch has the newer file without ever blocking on the network.
  e.respondWith((async () => {
    const hit = await caches.match(req);
    const net = fetch(req).then((res) => {
      if (res && res.ok) caches.open(CACHE).then((c) => c.put(req, res.clone()));
      return res;
    }).catch(() => null);
    return hit || (await net) || Response.error();
  })());
});
